#!/bin/sh

command -v python >/dev/null 2>&1 || { echo >&2 "Could not find python in your path (test262 requires it)."; exit 1; }

EXEC=`command -v d8 || command -v js` || { echo >&2 "Could not find the d8 or js executables in your path."; exit 1; }
CMD=`basename $EXEC`
INTL=../Intl.complete.js
TESTDIR=./test262
TEST262="$TESTDIR/tools/packaging/test262.py"

# TODO: Need to get this working with multiple locale files
if [ "$CMD" = "js" ]; then
    python $TEST262 --command "$EXEC -f $INTL -f test262assist.js -f" --tests="$TESTDIR" --summary intl402 > ./test262.log
else
    python $TEST262 --command "$EXEC $INTL test262assist.js" --tests="$TESTDIR" --summary intl402 > ./test262.log
fi
